# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3afe68f82d7ed6b34ed70321d0450d68fe28c207205ee188ca6129a90fc563c8c1028880e0f07ef739174c7415365cc3849a0618e1f7d19d79e99d9c8f7e8097

test:
  secret_key_base: f7ccfa23f2ba8be851b9f27a205f1b2cf9d22ebb44e45188b1bf3b87e36cf298ac2ae02097dd9c58875303c50071980e30259844ce328d62f3b4c2f9cff375a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
